In [46]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_squared_error

In [60]:
csv= pd.read_csv('F:/TipAmount_1.csv')

In [61]:
csv

Bill_Amount  Tip
0           100   10
1            50    5
2           200   10
3           500   20
4          1000   50
5          2000  100
6           600   20
7           800   20
8           900   20
9           650   20
10          700   20
11          950   20
12          850   20
13          830   20
14         1150   30
15         1250   30
16         1350   30
17         1450   30
18         1850   50
19         1950   50

In [62]:
df_x = pd.DataFrame(csv.Bill_Amount)
df_y = pd.DataFrame(csv.Tip)

In [63]:
df_x.describe()

Bill_Amount
count    20.000000
mean    956.500000
std     565.501873
min      50.000000
25%     637.500000
50%     875.000000
75%    1275.000000
max    2000.000000

In [64]:
reg = linear_model.LinearRegression()

In [65]:
x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.2, random_state=4)

In [66]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [67]:
reg.coef_

array([[0.03501638]])

In [68]:
reg.intercept_

array([-3.95519037])

In [69]:
a = reg.predict(x_test)

In [70]:
a

array([[64.32674494],
       [13.55299817],
       [60.82510724],
       [17.05463588]])

In [71]:
y_test

Tip
19   50
3    20
18   50
6    20

In [72]:
mean_squared_error(a,y_test)

93.1693924252879